const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
let lastPayload=null,lastIdemKey=null;
function newIdemKey(){return 'idem_'+(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36))}
$('#idem_key').value=newIdemKey();
function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function stampClass(d){return d==='APPROVE'?'approve':d==='STEP_UP'?'stepup':'decline'}
let usersCache=[];
let selectedRecipient=null;
let searchTimer=null;
async function loadUsers(search=''){
  const box=$('#recipient-results');
  box.classList.add('show');
  box.innerHTML='<div class="search-loading">Searching recipients…</div>';
  try{
    const r=await fetch('/api/users?search='+encodeURIComponent(search));
    if(!r.ok) throw new Error('Unable to load recipients');
    const users=await r.json(); usersCache=users;
    if(!users.length){box.innerHTML='<div class="search-empty">No recipients found.</div>';return;}
    box.innerHTML=users.map(u=>`<div class="recipient-option" data-user-id="${esc(u.user_id)}" data-name="${esc(u.name)}"><div class="recipient-avatar">${esc((u.name||'?').trim().charAt(0).toUpperCase())}</div><div><b>${esc(u.name)}</b><small>${esc(u.user_id)} • ${u.tx_count||0} previous payments</small></div></div>`).join('');
    box.querySelectorAll('.recipient-option').forEach(el=>el.addEventListener('click',()=>selectRecipient(el.dataset.userId,el.dataset.name)));
  }catch(e){box.innerHTML='<div class="search-empty">Unable to load recipients.</div>'}
}
function selectRecipient(id,name){
  selectedRecipient={id,name}; $('#user_id').value=id; $('#recipient-search').value=name;
  $('#selected-recipient').innerHTML=`<span>👤</span><div><b>${esc(name)}</b><small>${esc(id)} • Recipient selected</small></div>`;
  $('#recipient-results').classList.remove('show');
}
$('#recipient-search').addEventListener('input',()=>{clearTimeout(searchTimer);const q=$('#recipient-search').value.trim();searchTimer=setTimeout(()=>loadUsers(q),180)});
$('#recipient-search').addEventListener('focus',()=>{if(!selectedRecipient || !$('#recipient-results').children.length)loadUsers($('#recipient-search').value.trim())});
document.addEventListener('click',e=>{if(!e.target.closest('.recipient-picker'))$('#recipient-results').classList.remove('show')});
loadUsers();
$$('.tab').forEach(t=>t.addEventListener('click',()=>{ $$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#view-'+t.dataset.view).classList.add('active');if(t.dataset.view==='ops')refreshOps();if(t.dataset.view==='transactions')refreshTransactions()}));
$('#pay-form').addEventListener('submit',async e=>{e.preventDefault();if(!$('#user_id').value){$('#result-empty').style.display='none';$('#result-body').style.display='block';$('#result-body').innerHTML='<div class="warning-panel"><b>Select a recipient first.</b><br><small>Search for a person and choose them before paying.</small></div>';return}const payload={user_id:$('#user_id').value,amount:Number($('#amount').value),device_id:$('#device_id').value,location:$('#location').value,merchant:$('#merchant').value};const key=newIdemKey();$('#idem_key').value=key;lastPayload=payload;lastIdemKey=key;await sendPayment(payload,key)});
$('#merchant').addEventListener('change',()=>{});
async function sendPayment(payload,key){const btn=$('#submit-btn');btn.disabled=true;btn.textContent='Checking payment…';$('#result-empty').style.display='none';$('#result-body').style.display='block';$('#result-subtitle').textContent='FraudGuard is screening your payment…';$('#result-body').innerHTML='<div class="result-empty"><div class="empty-icon">🔍</div><h3>Securing your payment</h3><p>✓ Payment details<br>✓ Device verification<br>✓ Location check<br>⟳ Fraud screening</p></div>';await new Promise(r=>setTimeout(r,650));try{const res=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(payload)});const body=await res.json();renderResult(body,res.status,payload)}catch(err){renderError(err.message)}finally{btn.disabled=false;btn.textContent='🔒 Pay Securely'}}
function renderResult(body,status,payload){const panel=$('#result-body');if(body.error){panel.innerHTML='<div class="danger-panel">'+esc(body.error)+'</div>';return}const replay=body._replayed;const icon=body.decision==='APPROVE'?'✓':body.decision==='STEP_UP'?'🔐':'⚠️';const title=body.decision==='APPROVE'?'Payment Approved':body.decision==='STEP_UP'?'One more security check':'Payment Blocked';const state=body.state||'';let html=`<div class="decision-box"><div class="decision-icon">${icon}</div><h2>${title}</h2><div class="amount-result">${money(payload.amount)}</div><div class="merchant-result">${esc(payload.merchant)}</div></div>`;if(replay)html+='<div class="warning-panel"><b>🔒 Duplicate request detected</b><br><small>This payment was already processed. No second charge was created.</small></div>';if(body.decision==='APPROVE'){html+=`<div class="success-panel">✓ Your payment passed FraudGuard security checks.</div>`}else if(body.decision==='DECLINE'){html+=`<div class="danger-panel"><b>Your money has NOT been charged.</b><br><small>We could not safely authorize this payment.</small></div>`}else{html+=`<div class="warning-panel"><b>We noticed something unusual.</b><br><small>Complete the security check below to authorize this payment.</small></div>`}html+=`<div class="result-details"><div class="detail"><span>Risk score</span><b>${body.risk_score}/100</b></div><div class="detail"><span>Transaction</span><b>${esc(body.tx_id)}</b></div><div class="detail"><span>Status</span><b>${esc(friendlyState(state))}</b></div><div class="detail"><span>Decision</span><b>${esc(body.decision)}</b></div></div>`;if(body.explanation?.length){html+='<ul class="reason-list">';body.explanation.forEach(f=>html+=`<li><span>• ${esc(f.detail||f.factor)}</span><b>+${f.contribution}</b></li>`);html+='</ul>'}if(body.decision==='STEP_UP'&&state==='STEP_UP_REQUIRED'){html+=`<div class="otp-box"><label>Enter security OTP <small>(Demo OTP: ${esc(body.demo_otp)})</small></label><input id="otp-input" maxlength="6" inputmode="numeric" placeholder="• • • • • •"><button class="primary big" id="verify-otp-btn" style="margin-top:10px">Verify Payment</button></div>`}panel.innerHTML=html;$('#result-subtitle').textContent=body.decision==='APPROVE'?'Payment completed successfully.':body.decision==='STEP_UP'?'Verification required to continue.':'Payment was blocked for your protection.';const vb=$('#verify-otp-btn');if(vb)vb.addEventListener('click',async()=>{vb.disabled=true;vb.textContent='Verifying…';const res=await fetch(`/api/payments/${body.tx_id}/verify-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({otp:$('#otp-input').value})});const r=await res.json();if(r.result==='VERIFIED'){renderVerified(r,payload)}else{panel.innerHTML+=`<div class="danger-panel">✕ Verification failed. The payment was declined.</div>`}vb.disabled=false})}
function renderVerified(r,p){$('#result-body').innerHTML=`<div class="decision-box"><div class="decision-icon">✓</div><h2>Payment Verified</h2><div class="amount-result">${money(p.amount)}</div><div class="merchant-result">${esc(p.merchant)}</div></div><div class="success-panel">✓ OTP verified — payment authorized successfully.</div><div class="result-details"><div class="detail"><span>Transaction</span><b>${esc(r.tx_id)}</b></div><div class="detail"><span>Status</span><b>${esc(friendlyState(r.state))}</b></div></div>`;$('#result-subtitle').textContent='Your payment has been securely authorized.'}
function friendlyState(s){return ({SETTLED:'Settled',PENDING_SETTLEMENT:'Pending settlement',STEP_UP_REQUIRED:'Verification required',DECLINED:'Declined',AUTHORIZED:'Authorized'})[s]||s}
function renderError(msg){$('#result-empty').style.display='none';$('#result-body').style.display='block';$('#result-body').innerHTML='<div class="danger-panel">Request failed: '+esc(msg)+'</div>'}
async function refreshTransactions(){try{const r=await fetch('/api/transactions');const txs=await r.json();let approved=0,pending=0,blocked=0;txs.forEach(t=>{if(t.state==='SETTLED')approved++;if(t.state==='PENDING_SETTLEMENT')pending++;if(t.state==='DECLINED')blocked++});$('#user-approved').textContent=approved;$('#user-pending').textContent=pending;$('#user-blocked').textContent=blocked;$('#transaction-list').innerHTML=txs.length?txs.slice(0,30).map(t=>`<div class="transaction-item"><div class="transaction-main"><div class="tx-icon">${t.state==='DECLINED'?'⚠️':t.state==='PENDING_SETTLEMENT'?'⏳':'💳'}</div><div><b>${esc(t.merchant)}</b><span>${esc(t.tx_id)} • ${new Date(t.created_at*1000).toLocaleString()}</span></div></div><div class="tx-right"><strong>${money(t.amount)}</strong><span class="status-pill ${statusClass(t.state)}">${esc(friendlyState(t.state))}</span></div></div>`).join(''):'<div class="loading">No transactions yet.</div>'}catch(e){$('#transaction-list').innerHTML='<div class="loading">Unable to load transactions.</div>'}}
function statusClass(s){return s==='SETTLED'?'status-approved':s==='DECLINED'?'status-declined':s==='STEP_UP_REQUIRED'?'status-stepup':'status-pending'}
$('#refresh-transactions').addEventListener('click',refreshTransactions);
$('#toggle-outage').addEventListener('click',async()=>{const s=await (await fetch('/api/admin/status')).json();await fetch('/api/admin/outage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({force:!s.outage.force_outage})});refreshOps()});
$('#reconcile-now').addEventListener('click',async()=>{const b=$('#reconcile-now');b.disabled=true;b.textContent='Reconciling…';await fetch('/api/admin/reconcile-now',{method:'POST'});await refreshOps();b.disabled=false;b.textContent='↻ Run reconciliation'});
$('#ops-replay').addEventListener('click',async()=>{const out=$('#replay-result');if(!lastPayload){out.innerHTML='<span style="color:#b54708">Make a payment first in the Pay tab.</span>';return}out.textContent='Sending same request…';const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':lastIdemKey},body:JSON.stringify(lastPayload)});const b=await r.json();out.innerHTML=b._replayed?'✓ Duplicate detected — previous response returned. No new transaction created.':'Request processed.';refreshOps()});
async function refreshOps(){try{const [tr,sr]=await Promise.all([fetch('/api/transactions'),fetch('/api/admin/status')]);const txs=await tr.json(),s=await sr.json();let a=0,r=0,d=0,p=0;txs.forEach(t=>{if(t.decision==='APPROVE')a++;if(t.decision==='STEP_UP')r++;if(t.decision==='DECLINE')d++;if(t.state==='PENDING_SETTLEMENT')p++});$('#count-approved').textContent=a;$('#count-review').textContent=r;$('#count-declined').textContent=d;$('#count-pending').textContent=p;const outage=s.outage.force_outage;$('#outage-status').innerHTML=`<span class="status-dot" style="background:${outage?'var(--red)':'var(--green)'}"></span> Settlement network ${outage?'simulated outage':'operational'}`;$('#toggle-outage').textContent=outage?'Restore settlement network':'Simulate settlement outage';$('#ledger-table tbody').innerHTML=txs.map(t=>`<tr><td>${esc(t.tx_id)}</td><td>${esc(t.user_id)}</td><td>${money(t.amount)}</td><td><b>${t.risk_score}</b></td><td>${esc(t.decision)}</td><td><span class="status-pill ${statusClass(t.state)}">${esc(friendlyState(t.state))}</span></td><td>${t.settlement_attempts}</td><td>${new Date(t.created_at*1000).toLocaleTimeString()}</td></tr>`).join('')||'<tr><td colspan="8">No transactions yet.</td></tr>';$('#recon-feed').innerHTML=s.recent_events?.slice().reverse().map(e=>`<li>${new Date(e.t*1000).toLocaleTimeString()} — ${esc(e.event)}</li>`).join('')||'<li>No reconciliation activity yet.</li>'}catch(e){console.error(e)}}
setInterval(()=>{if($('#view-ops').classList.contains('active'))refreshOps()},3000);setInterval(()=>{if($('#view-transactions').classList.contains('active'))refreshTransactions()},5000);
